# QUES: FINDING OUT THE MODEL WITH THE HELP OF CROSS VALIDATION
ADHIRAJ PRATAP SINGH

In [56]:
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits
import numpy as np
#import pandas as pd

In [57]:
data=load_digits()

In [37]:
from sklearn.model_selection import train_test_split

In [38]:
data.keys()

dict_keys(['data', 'target', 'frame', 'feature_names', 'target_names', 'images', 'DESCR'])

In [39]:
x_train , x_test , y_train , y_test= train_test_split(data.data, data.target , test_size=0.2)

In [40]:
lr = LinearRegression()
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

0.5467833911401663

In [41]:
svm=SVC()
svm.fit(x_train,y_train)
svm.score(x_test, y_test)

0.9944444444444445

In [42]:
rfc=RandomForestClassifier(n_estimators=10)
rfc.fit(x_train,y_train)
rfc.score(x_test, y_test)

0.9527777777777777

CHECKING THE MODEL NUMBER OF TIMES AGAIN AND AGAIN WE USE KFOLD

In [43]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [44]:
for train_index , test_index in kf.split(data):
    print(train_index , test_index)

[3 4 5 6] [0 1 2]
[0 1 2 5 6] [3 4]
[0 1 2 3 4] [5 6]


In [45]:
def get_score(model , x_train , x_test , y_train , y_test):
    model.fit(x_train , y_train)
    return model.score(x_test,y_test)

In [46]:
get_score(LinearRegression(),x_train , x_test , y_train , y_test)

0.5467833911401663

In [47]:
get_score(SVC(),x_train , x_test , y_train , y_test)

0.9944444444444445

In [48]:
get_score(RandomForestClassifier(),x_train , x_test , y_train , y_test)

0.9833333333333333

In [49]:
#DOING SAME AS LINE 13

scores_l=[]
scores_svc=[]
scores_rc=[]

for train_index , test_index in kf.split(data):
    x_train , x_test , y_train , y_test= train_test_split(data.data, data.target , test_size=0.2)

    scores_l.append(get_score(LinearRegression(),x_train , x_test , y_train , y_test))
    scores_svc.append(get_score(SVC(),x_train , x_test , y_train , y_test))
    scores_rc.append(get_score(RandomForestClassifier(),x_train , x_test , y_train , y_test))

In [50]:
scores_l

[0.543727282183934, 0.6065128057329072, 0.5055013323856219]

In [51]:
scores_svc

[0.9833333333333333, 0.9833333333333333, 0.9805555555555555]

In [52]:
scores_rc

[0.9833333333333333, 0.9638888888888889, 0.975]

In [60]:
data.keys()

dict_keys(['data', 'target', 'frame', 'feature_names', 'target_names', 'images', 'DESCR'])

# APPLYING CROSS VALIDATION

In [53]:
from sklearn.model_selection import cross_val_score

In [61]:
cross_val_score( LogisticRegression(),data.data,data.target)

C:\Users\wwwpr\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\wwwpr\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [62]:
cross_val_score( LinearRegression(),data.data,data.target)

array([0.48346048, 0.5583603 , 0.57534522, 0.5056632 , 0.40995457])

In [63]:
cross_val_score( SVC(),data.data,data.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [66]:
cross_val_score( RandomForestClassifier(n_estimators=20),data.data,data.target)

array([0.93611111, 0.90555556, 0.94986072, 0.95264624, 0.90807799])

# CONCLUSION

AS WE FOUND SVC model giving out the best result so we will choose SVC model